### ISSUE TITLE
Found example queue thread dead. Restarting.

### ISSUE THREAD

**Issue by mohd1996** [abisee/pointer-generator#110]
I got this error, executing with default parameters on google colab:

> ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
ERROR:tensorflow:Found example queue thread dead. Restarting.
Exception in thread Thread-10957:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/content/batcher.py", line 306, in fill_example_queue
    example = Example(article, abstract_sentences, self._vocab, self._hps) # Process into an Example.
  File "/content/batcher.py", line 48, in __init__
    if len(article_words) > hps.max_enc_steps.value:
AttributeError: 'int' object has no attribute 'value'
Exception in thread Thread-10958:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/content/batcher.py", line 306, in fill_example_queue
    example = Example(article, abstract_sentences, self._vocab, self._hps) # Process into an Example.
  File "/content/batcher.py", line 48, in __init__
    if len(article_words) > hps.max_enc_steps.value:
AttributeError: 'int' object has no attribute 'value'

**Comment by erinkraemer** [comment]
how did you solve this error?
