### ISSUE TITLE
when I run the "beam search decoding", an exception happened, please help!

### ISSUE THREAD

**Issue by mingChennjupt** [abisee/pointer-generator#147]
`python run_summarization.py --mode=decode --data_path/home/intern/chenming_test/cnn-dailymail-master/finished_files/chunked/val_* --vocab_path=/home/intern/chenming_test/cnn-dailymail-master/finished_files/vocab --log_root=/home/intern/chenming_test/cnn-dailymail-master/finished_files/a/log/directory --exp_name=myexperiment
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: /home/intern/chenming_test/cuda8/cuda/lib64:/home/intern/chenming_test/cuda8/lib64:/home/intern/chenming_test/cuda8/cuda/lib64:/home/intern/chenming_test/cuda8/lib64:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "run_summarization.py", line 324, in <module>
    tf.app.run()
  File "/home/intern/anaconda3/envs/chenming2/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run_summarization.py", line 269, in main
    raise Exception("Problem with flags: %s" % unused_argv)
Exception: Problem with flags: ['run_summarization.py', '--data_path/home/intern/chenming_test/cnn-dailymail-master/finished_files/chunked/val_*']`

i can't solve this problem, please help! thx

**Comment by mingChennjupt** [comment]
Exception: Problem with flags: ['run_summarization.py', '--data_path/home/intern/chenming_test/cnn-dailymail-master/finished_files/chunked/val_*']

**Comment by ojassm** [comment]
@mingChennjupt 
It is really simple. You forgot to add a '=' while defining your data path. --data_path **=**

**Comment by mingChennjupt** [comment]
@ojassm oh, I'm so stupid, thank you very much!!
