### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'int' and 'Flag'

### ISSUE THREAD

**Issue by WSChange** [abisee/pointer-generator#179]
When I run the file run_summarization.py,the problem is occuring. Does anyone help me?
Traceback (most recent call last):
  File "\pointer-generator-master\run_summarization.py", line 328, in <module>
    tf.app.run()
  File "\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "\pointer-generator-master\run_summarization.py", line 307, in main
    batcher = Batcher(FLAGS.data_path, vocab, hps, single_pass=FLAGS.single_pass)
  File "\pointer-generator-master\batcher.py", line 238, in __init__
    self._example_queue = Queue.Queue(self.BATCH_QUEUE_MAX * self._hps.batch_size)
TypeError: unsupported operand type(s) for *: 'int' and 'Flag'

**Comment by THUwjy** [comment]
Can you tell me how did you deal with this, I met the exception too.
