### ISSUE TITLE
Throws Exception during threading (last 4)

### ISSUE THREAD

**Issue by Adityagrao** [abisee/pointer-generator#92]
` 
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/pointer-generator/src/batcher.py", line 309, in fill_batch_queue
    for _ in range(self._hps.batch_size * self._bucketing_cache_size):
TypeError: unsupported operand type(s) for *: 'Flag' and 'int'
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/pointer-generator/src/batcher.py", line 309, in fill_batch_queue
    for _ in range(self._hps.batch_size * self._bucketing_cache_size):
TypeError: unsupported operand type(s) for *: 'Flag' and 'int'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/pointer-generator/src/batcher.py", line 309, in fill_batch_queue
    for _ in range(self._hps.batch_size * self._bucketing_cache_size):
TypeError: unsupported operand type(s) for *: 'Flag' and 'int'
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/pointer-generator/src/batcher.py", line 309, in fill_batch_queue
    for _ in range(self._hps.batch_size * self._bucketing_cache_size):
TypeError: unsupported operand type(s) for *: 'Flag' and 'int' 

`

I think there are compatibility issues with the thread.
both ._hps.batch_size and ._bucketing_cache_size are both defined as int.

**Comment by leobouscarrat** [comment]
Could it be linked to [that](https://stackoverflow.com/questions/49312591/tensorflow-code-typeerror-unsupported-operand-types-for-int-and-flag) ?

**Comment by Adityagrao** [comment]
@leobouscarrat  that really helped, thanks :+1:
